# Generated by Django 5.1.6 on 2025-03-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cargo", models.CharField(max_length=100)),
                ("nascimento", models.DateField()),
                ("tipo_cargo", models.DateField()),
                ("data_admissao", models.DateField()),
                ("data_saida", models.DateField()),
            ],
        ),
    ]
